export { modals } from './modal.js'
export { sliders } from './slider.js'
export { form } from './forms.js'
export { mask } from './maskNum.js'
export { checkInputs } from './checkTextInputs.js'
export { showMoreStyle } from './showMore.js'